FPAttributeValueFile
n SubType="IVI"
n SubVersion="1"

v LimitTestType DataType="i"
 AGB29XX_VAL_LIMITTEST_TYPE_COMPLIANCE (1)
  "Compliance test type"

 AGB29XX_VAL_LIMITTEST_TYPE_LIMIT (2)
  "Limit test type"


v LimitTestInputDataValue DataType="i"
 AGB29XX_VAL_LIMITTEST_INPUT_DATA_VALUE_MATH (0)
  "Math data value"

 AGB29XX_VAL_LIMITTEST_INPUT_DATA_VALUE_CURRENT (1)
  "Current data value"

 AGB29XX_VAL_LIMITTEST_INPUT_DATA_VALUE_VOLTAGE (2)
  "Voltage data value"

 AGB29XX_VAL_LIMITTEST_INPUT_DATA_VALUE_RESISTANCE (3)
  "Resistance data value."


v LimitTestJudgementCriteria DataType="i"
 AGB29XX_VAL_LIMITTEST_JUDGEMENT_CRITERIA_IN (0)
  "In Criteria"

 AGB29XX_VAL_LIMITTEST_JUDGEMENT_CRITERIA_OUT (1)
  "Out Criteria"


v MeasurementAutoRangingMode DataType="i"
 AGB29XX_VAL_MEASUREMENT_AUTO_RANGING_MODE_NORMAL (0)
  "Normal mode."

 AGB29XX_VAL_MEASUREMENT_AUTO_RANGING_MODE_SPEED (1)
  "Speed mode"

 AGB29XX_VAL_MEASUREMENT_AUTO_RANGING_MODE_RESOLUTION (2)
  "Resolution mode."


v MeasurementResistanceMode DataType="i"
 AGB29XX_VAL_MEASUREMENT_RESISTANCE_MODE_MANUAL (0)
  "Manual resistance mode."

 AGB29XX_VAL_MEASUREMENT_RESISTANCE_MODE_AUTO (1)
  "Auto resistance mode."


v CompositeLimitTestMode DataType="i"
 AGB29XX_VAL_COMPOSITE_LIMIT_TEST_MODE_GRADING (0)
  "Operation mode - Grading"

 AGB29XX_VAL_COMPOSITE_LIMIT_TEST_MODE_SORTING (1)
  "Operation mode - Sorting"


v ArmTriggerBypass DataType="i"
 AGB29XX_VAL_ARM_TRIGGER_BYPASS_OFF (0)
  "Bypass off."

 AGB29XX_VAL_ARM_TRIGGER_BYPASS_ONCE (1)
  "Bypass once."


v ArmTriggerSource DataType="i"
 AGB29XX_VAL_ARM_TRIGGER_SOURCE_INT1 (0)
  "Source INTernal1"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_INT2 (1)
  "Source INTernal2"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT1 (2)
  "Source EXTernal1"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT2 (3)
  "Source EXTernal2"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT3 (4)
  "Source EXTernal3"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT4 (5)
  "Source EXTernal4"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT5 (6)
  "Source EXTernal5"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT6 (7)
  "Source EXTernal6"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT7 (8)
  "Source EXTernal7"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT8 (9)
  "Source EXTernal8"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT9 (10)
  "Source EXTernal9"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT10 (11)
  "Source EXTernal10"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT11 (12)
  "Source EXTernal11"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT12 (13)
  "Source EXTernal12"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT13 (14)
  "Source EXTernal3"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_EXT14 (15)
  "Source EXTernal14"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_AINT (17)
  "Source AINT"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_BUS (18)
  "Source BUS"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_TIMER (19)
  "Source TIMER"

 AGB29XX_VAL_ARM_TRIGGER_SOURCE_TRIGGER_LAN (16)


v TraceDataType DataType="i"
 AGB29XX_VAL_TRACE_DATA_TYPE_MATH (0)
  "Math data type"

 AGB29XX_VAL_TRACE_DATA_TYPE_SENSE (1)
  "Sense data type"

 AGB29XX_VAL_TRACE_DATA_TYPE_LIMIT (2)
  "Limit data type (Supported models: B2901A, B2902A, B2911A, B2912A)"


v TraceBufferControl DataType="i"
 AGB29XX_VAL_TRACE_BUFFER_CONTROL_NEXT (0)
  "Buffer control - Next"

 AGB29XX_VAL_TRACE_BUFFER_CONTROL_NEVER (1)
  "Buffer control - Never"


v TraceOperation DataType="i"
 AGB29XX_VAL_TRACE_OPERATION_MEAN (0)
  "Statistical operation - Mean"

 AGB29XX_VAL_TRACE_OPERATION_STANDARD_DEVIATION (1)
  "Statistical operation - Standard deviation"

 AGB29XX_VAL_TRACE_OPERATION_MAXIMUM (2)
  "Statistical operation - Maximum"

 AGB29XX_VAL_TRACE_OPERATION_MINIMUM (3)
  "Statistical operation - Minimum"

 AGB29XX_VAL_TRACE_OPERATION_PEAK_TO_PEAK (4)
  "Statistical operation - Peak to Peak"


v TraceTimeStampFormat DataType="i"
 AGB29XX_VAL_TRACE_TIME_STAMP_FORMAT_ABSOLUTE (0)
  "Absolute time stamp format"

 AGB29XX_VAL_TRACE_TIME_STAMP_FORMAT_DELTA (1)
  "Delta time stamp format"


v FormatByteOrder DataType="i"
 AGB29XX_VAL_FORMAT_BYTE_ORDER_NORMAL (0)
  "Normal byte order"

 AGB29XX_VAL_FORMAT_BYTE_ORDER_SWAPPED (1)
  "Swapped byte order."


v FormatType DataType="i"
 AGB29XX_VAL_FORMAT_TYPE_ASCII (0)
  "ASCII format"

 AGB29XX_VAL_FORMAT_TYPE_REAL32 (1)
  "Real32 format"

 AGB29XX_VAL_FORMAT_TYPE_REAL64 (2)
  "Real64 format"


v DisplayResolution DataType="i"
 AGB29XX_VAL_DISPLAY_RESOLUTION_DIGIT4 (0)
  "4 digit resolution"

 AGB29XX_VAL_DISPLAY_RESOLUTION_DIGIT5 (1)
  "5 digit resolution"

 AGB29XX_VAL_DISPLAY_RESOLUTION_DIGIT6 (2)
  "6 digit resolution"

 AGB29XX_VAL_DISPLAY_RESOLUTION_DIGIT7 (3)
  "7 digit resolution"


v DisplayMode DataType="i"
 AGB29XX_VAL_DISPLAY_MODE_SINGLE1 (0)
  "Single1 mode"

 AGB29XX_VAL_DISPLAY_MODE_SINGLE2 (1)
  "Single2 mode"

 AGB29XX_VAL_DISPLAY_MODE_DUAL (2)
  "Dual mode"

 AGB29XX_VAL_DISPLAY_MODE_GRAPH (3)
  "Graph mode"

 AGB29XX_VAL_DISPLAY_MODE_ROLL (4)
  "Roll mode"


v DisplayImageFormat DataType="i"
 AGB29XX_VAL_DISPLAY_IMAGE_FORMAT_JPG (0)
  "JPG format"

 AGB29XX_VAL_DISPLAY_IMAGE_FORMAT_BMP (1)
  "BMP format"

 AGB29XX_VAL_DISPLAY_IMAGE_FORMAT_PNG (2)
  "PNG format"

 AGB29XX_VAL_DISPLAY_IMAGE_FORMAT_WMF (3)
  "WMF format"


v ProgramStatus DataType="i"
 AGB29XX_VAL_PROGRAM_STATUS_RUN (0)
  "Program status - run"

 AGB29XX_VAL_PROGRAM_STATUS_PAUSE (1)
  "Program status - pause"

 AGB29XX_VAL_PROGRAM_STATUS_STEP (2)
  "Program status - step"

 AGB29XX_VAL_PROGRAM_STATUS_STOP (3)
  "Program status - stop"

 AGB29XX_VAL_PROGRAM_STATUS_CONTINUE (4)
  "Program status - continue"


v TransientCurrentVoltageMode DataType="i"
 AGB29XX_VAL_TRANSIENT_CURRENT_VOLTAGE_MODE_FIXED (0)
  "Fixed mode"

 AGB29XX_VAL_TRANSIENT_CURRENT_VOLTAGE_MODE_LIST (1)
  "List mode"

 AGB29XX_VAL_TRANSIENT_CURRENT_VOLTAGE_MODE_SWEEP (2)
  "Sweep mode"


v SweepDirection DataType="i"
 AGB29XX_VAL_SWEEP_DIRECTION_UP (0)
  "Up direction"

 AGB29XX_VAL_SWEEP_DIRECTION_DOWN (1)
  "Down direction"


v SweepOutputRangingMode DataType="i"
 AGB29XX_VAL_SWEEP_OUTPUT_RANGING_MODE_BEST (0)
  "Best output ranging mode"

 AGB29XX_VAL_SWEEP_OUTPUT_RANGING_MODE_AUTO (1)
  "Auto output ranging mode"

 AGB29XX_VAL_SWEEP_OUTPUT_RANGING_MODE_FIXED (2)
  "Fixed output ranging mode."


v SweepOutputScale DataType="i"
 AGB29XX_VAL_SWEEP_OUTPUT_SCALE_LINEAR (0)
  "Liner output scale."

 AGB29XX_VAL_SWEEP_OUTPUT_SCALE_LOGARITHMIC (1)
  "Logarithmic output scale."


v SweepMode DataType="i"
 AGB29XX_VAL_SWEEP_MODE_SINGLE (0)
  "Single sweep mode"

 AGB29XX_VAL_SWEEP_MODE_DOUBLE (1)
  "Double sweep mode."


v TransientArbitraryWaveformShape DataType="i"
 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_EXPONENT (0)
  "Selects the exponential current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_RAMP (1)
  "Selects the ramp current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_SINUSOID (2)
  "Selects the sinusoid current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_SQUARE (3)
  "Selects the square current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_TRAPEZOID (4)
  "Selects the trapezoid current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_TRIANGLE (5)
  "Selects the triangle current or voltage waveform."

 AGB29XX_VAL_TRANSIENT_ARBITRARYWAVEFORM_SHAPE_USER_DEFINED (6)
  "Selects the user defined current or voltage waveform."


v OutputLowTerminalState DataType="i"
 AGB29XX_VAL_OUTPUT_LOW_TERMINAL_STATE_FLOAT (0)
  "Float low terminal state"

 AGB29XX_VAL_OUTPUT_LOW_TERMINAL_STATE_GROUND (1)
  "Ground low terminal state"


v OutputOffCondition DataType="i"
 AGB29XX_VAL_OUTPUT_OFF_CONDITION_HIZ (0)
  "HiZ Off condition"

 AGB29XX_VAL_OUTPUT_OFF_CONDITION_NORMAL (1)
  "Normal Off condition"

 AGB29XX_VAL_OUTPUT_OFF_CONDITION_ZERO (2)
  "Zero Off condition"


v OutputType DataType="i"
 AGB29XX_VAL_OUTPUT_TYPE_CURRENT (0)
  "Current Output type"

 AGB29XX_VAL_OUTPUT_TYPE_VOLTAGE (1)
  "Voltage Output type"


v OutputShape DataType="i"
 AGB29XX_VAL_OUTPUT_SHAPE_DC (0)
  "DC shape"

 AGB29XX_VAL_OUTPUT_SHAPE_PULSE (1)
  "Pulse shape"


v ExternalFilter DataType="i"
 AGB29XX_VAL_EXTERNAL_FILTERULNF (0)
  "Ultra Low Noise Filter type"

 AGB29XX_VAL_EXTERNAL_FILTERLNF (1)
  "Low Noise Filter type"


v OutputResistanceOperationMode DataType="i"
 AGB29XX_VAL_OUTPUT_RESISTANCE_OPERATION_MODE_EMULATE (0)
  "Emulate Operation mode."

 AGB29XX_VAL_OUTPUT_RESISTANCE_OPERATION_MODE_FIXED (1)
  "Fixed Operation mode."


v ArmSourceDetection DataType="i"
 AGB29XX_VAL_IVILXISYNC_DETECTION_RISE (0)
  "Configures the LXI device to arm on the rising edge of the arm source."

 AGB29XX_VAL_IVILXISYNC_DETECTION_FALL (1)
  "Configures the  LXI device  to arm on the falling edge of the arm source."

 AGB29XX_VAL_IVILXISYNC_DETECTION_HIGH (2)
  "Configures the LXI device to arm while the arm source is high, that is, while it "
  "remains true."

 AGB29XX_VAL_IVILXISYNC_DETECTION_LOW (3)
  "Configures the LXI device to arm while the arm source is low, that is, while it remains "
  "false."


v EventDriveMode DataType="i"
 AGB29XX_VAL_IVILXISYNC_EVENT_DRIVEN (0)
  "Enables the event in driven mode."

 AGB29XX_VAL_IVILXISYNC_EVENT_OFF (1)
  "Disables the event."

 AGB29XX_VAL_IVILXISYNC_EVENT_WIREDOR (2)
  "Enables the event in wired-OR mode."


v SourceSlope DataType="i"
 AGB29XX_VAL_IVILXISYNC_SLOPE_RISE (0)
  "The event will be transmitted with a rising edge."

 AGB29XX_VAL_IVILXISYNC_SLOPE_FALL (1)
  "The event will be transmitted with a falling edge."


v TriggerSource DataType="i"
 AGB29XX_VAL_TRIG_IMMEDIATE (0)
  "The power supply does not wait for a trigger before changing the output signal."

 AGB29XX_VAL_TRIG_EXTERNAL (1)
  "The power supply waits for an external trigger before changing the output signal."

 AGB29XX_VAL_SOFTWARE_TRIG (2)
  "The power supply waits for the Send Software Trigger function to execute before changing "
  "the output signal."

 AGB29XX_VAL_TRIG_TTL0 (3)
  "The power supply waits for a trigger on the TTL 0 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL1 (4)
  "The power supply waits for a trigger on the TTL 1 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL2 (5)
  "The power supply waits for a trigger on the TTL 2 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL3 (6)
  "The power supply waits for a trigger on the TTL 3 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL4 (7)
  "The power supply waits for a trigger on the TTL 4 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL5 (8)
  "The power supply waits for a trigger on the TTL 5 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL6 (9)
  "The power supply waits for a trigger on the TTL 6 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_TTL7 (10)
  "The power supply waits for a trigger on the TTL 7 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_ECL0 (11)
  "The power supply waits for a trigger on the ECL 0 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_ECL1 (12)
  "The power supply waits for a trigger on the ECL 1 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_PXI_STAR (13)
  "The power supply waits for a trigger on the PXI Star line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_0 (14)
  "The power supply waits for a trigger on the RTSI 0 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_1 (15)
  "The power supply waits for a trigger on the RTSI 1 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_2 (16)
  "The power supply waits for a trigger on the RTSI 2 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_3 (17)
  "The power supply waits for a trigger on the RTSI 3 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_4 (18)
  "The power supply waits for a trigger on the RTSI 4 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_5 (19)
  "The power supply waits for a trigger on the RTSI 5 line before changing the output "
  "signal."

 AGB29XX_VAL_TRIG_RTSI_6 (20)
  "The power supply waits for a trigger on the RTSI 6 line before changing the output "
  "signal."


v TriggerSourceDetection DataType="i"
 AGB29XX_VAL_IVILXISYNC_SLOPE_RISE (0)
  "Configures the LXI device to trigger on the rising edge of the trigger source."

 AGB29XX_VAL_IVILXISYNC_SLOPE_FALL (1)
  "Configures the LXI device to trigger on the falling edge of the trigger source."


v CurrentLimitBehavior DataType="i"
 AGB29XX_VAL_CURRENT_REGULATE (0)
  "The power supply restricts the output voltage such that the output current is not "
  "greater than the value of the Current Limit attribute."

 AGB29XX_VAL_CURRENT_TRIP (1)
  "The power supply disables the output when the output current is equal to or greater "
  "than the value of the Current Limit attribute."


0 AgB29xx_GetAttributeViInt32 3 4 false g DataType="ViInt32"
0 AgB29xx_SetAttributeViInt32 3 4 false s DataType="ViInt32"
0 AgB29xx_CheckAttributeViInt32 3 4 false s DataType="ViInt32"
0 AgB29xx_GetAttributeViReal64 3 4 false g DataType="ViReal64"
0 AgB29xx_SetAttributeViReal64 3 4 false s DataType="ViReal64"
0 AgB29xx_CheckAttributeViReal64 3 4 false s DataType="ViReal64"
0 AgB29xx_GetAttributeViSession 3 4 false g DataType="ViSession"
0 AgB29xx_SetAttributeViSession 3 4 false s DataType="ViSession"
0 AgB29xx_CheckAttributeViSession 3 4 false s DataType="ViSession"
0 AgB29xx_GetAttributeViBoolean 3 4 false g DataType="ViBoolean"
0 AgB29xx_SetAttributeViBoolean 3 4 false s DataType="ViBoolean"
0 AgB29xx_CheckAttributeViBoolean 3 4 false s DataType="ViBoolean"
0 AgB29xx_GetAttributeViString 3 5 false g DataType="ViString"
0 AgB29xx_SetAttributeViString 3 4 false s DataType="ViString"
0 AgB29xx_CheckAttributeViString 3 4 false s DataType="ViString"
1 all "Inherent IVI Attributes"

2 all "Advanced Session Information"

3 all "Driver Setup" AGB29XX_ATTR_DRIVER_SETUP ViString g 
 "The driver setup string.  It is either specified in the Configuration Store or passed "
 "in the OptionString parameter of the Initialize function.  Driver setup is empty "
 "if the driver is not initialized."

3 all "I/O Resource Descriptor" AGB29XX_ATTR_IO_RESOURCE_DESCRIPTOR ViString g 
 "The resource descriptor specifies the connection to a physical device.  It is either "
 "specified in the Configuration Store or passed in the ResourceName parameter of the "
 "Initialize function.  It is empty if the driver is not initialized."

3 all "Logical Name" AGB29XX_ATTR_LOGICAL_NAME ViString g 
 "Logical Name identifies a driver session in the Configuration Store.  If Logical "
 "Name is not empty, the driver was initialized from information in the driver session. "
 " If it is empty, the driver was initialized without using the Configuration Store."

2 all "Driver Capabilities"

3 all "Class Group Capabilities" AGB29XX_ATTR_GROUP_CAPABILITIES ViString g 
 "A comma-separated list of the class capability groups implemented by the driver. "
 " Capability group names are documented in the IVI class specifications.  If the driver "
 "is not class compliant, the driver returns an empty string."

3 all "Supported Instrument Models" AGB29XX_ATTR_SUPPORTED_INSTRUMENT_MODELS ViString g 
 "A comma-separated list of instrument models that the IVI specific driver can control. "
 " The string does not include an abbreviation for the manufacturer if it is the same "
 "for all models."

2 all "Driver Identification"

3 all "Specific Driver Class Spec Major Version" AGB29XX_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION ViInt32 g 
 "Returns the major version number of the class specification in accordance with which "
 "the IVI specific driver was developed. Zero is returned if the driver is not compliant "
 "with a class specification."

3 all "Specific Driver Class Spec Minor Version" AGB29XX_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION ViInt32 g 
 "Returns the minor version number of the class specification in accordance with which "
 "the IVI specific driver was developed. Zero is returned if the driver is not compliant "
 "with a class specification."

3 all "Specific Driver Description" AGB29XX_ATTR_SPECIFIC_DRIVER_DESCRIPTION ViString g 
 "Returns a brief description of the IVI specific driver. The string that this attribute "
 "returns contains a maximum of 256 bytes including the NUL byte."

3 all "Specific Driver Prefix" AGB29XX_ATTR_SPECIFIC_DRIVER_PREFIX ViString g 
 "Returns the case-sensitive prefix of the user-callable functions that the IVI-C specific "
 "driver exports. The string that this attribute returns contains a maximum of 32 bytes "
 "including the NUL byte."

3 all "Specific Driver Revision" AGB29XX_ATTR_SPECIFIC_DRIVER_REVISION ViString g 
 "Returns version information about the IVI specific driver. The string that this attribute "
 "returns contains a maximum of 256 bytes including the NUL byte."

3 all "Specific Driver Vendor" AGB29XX_ATTR_SPECIFIC_DRIVER_VENDOR ViString g 
 "Returns the name of the vendor that supplies the IVI specific driver. The string "
 "that this attribute returns contains a maximum of 256 bytes including the NUL byte."

2 all "Instrument Identification"

3 all "Instrument Firmware Revision" AGB29XX_ATTR_INSTRUMENT_FIRMWARE_REVISION ViString g 
 "The firmware revision reported by the physical instrument.  If Simulation is enabled "
 "or the instrument is not capable of reporting the firmware revision, a string is "
 "returned that explains the condition."

3 all "Instrument Manufacturer" AGB29XX_ATTR_INSTRUMENT_MANUFACTURER ViString g 
 "The name of the manufacturer reported by the physical instrument.  If Simulation "
 "is enabled or the instrument is not capable of reporting the name of the manufacturer, "
 "a string is returned that explains the condition. Manufacturer is limited to 256 "
 "bytes"

3 all "Instrument Model" AGB29XX_ATTR_INSTRUMENT_MODEL ViString g 
 "The model number or name reported by the physical instrument.  If Simulation is enabled "
 "or the instrument is not capable of reporting the model number or name, a string "
 "is returned that explains the condition.  Model is limited to 256 bytes"

2 all "User Options"

3 all "Cache" AGB29XX_ATTR_CACHE ViBoolean gs 
 "Drivers may choose to always cache some instrument settings, never cache others, "
 "and optionally cache others, to avoid unecessary I/O to the instrument.  If True, "
 "the driver caches optionally cached instrument settings."

3 all "Interchange Check" AGB29XX_ATTR_INTERCHANGE_CHECK ViBoolean gs 
 "If True, the driver maintains a record of interchangeability warnings.  If the driver "
 "does not support interchangeability checking, attempts to set InterchangeCheck to "
 "True return an error."

3 all "Query Instrument Status" AGB29XX_ATTR_QUERY_INSTRUMENT_STATUS ViBoolean gs 
 "If True, the driver queries the instrument status at the end of each method or property "
 "that performs I/O to the instrument.  If an error is reported, use ErrorQuery to "
 "retrieve error messages one at a time from the instrument."

3 all "Range Check" AGB29XX_ATTR_RANGE_CHECK ViBoolean gs 
 "Drivers may choose to always validate some property/parameter values, never validate "
 "others, and optionally validate others, to avoid sending invalid commands to the "
 "instrument.  If True, the driver performs optional validations."

3 all "Record Value Coercions" AGB29XX_ATTR_RECORD_COERCIONS ViBoolean gs 
 "If True, the driver keeps a list of the value coercions it makes for ViInt32 and "
 "ViReal64 attributes.  If the driver does not support coercion recording, attempts "
 "to set RecordCoercions to True will return an error."

3 all "Simulate" AGB29XX_ATTR_SIMULATE ViBoolean gs 
 "If True, the driver does not perform I/O to the instrument, and returns simulated "
 "values for output parameters."

1 all "Arm"

2 all "Arm Count" AGB29XX_ATTR_IVILXISYNC_ARM_COUNT ViInt32 gs 
 "Specifies the number of times the arm has to occur to complete the arm loop; that "
 "is, the number of arms that are accepted before the measurement must be initiated "
 "again."

2 all "Arm Delay" AGB29XX_ATTR_IVILXISYNC_ARM_DELAY ViReal64 gs 
 "Specifies the delay from when the arm logic satisfied until the waiting for trigger "
 "state is entered.  The units are seconds."

2 all "Source"

3 all "Arm Source Count" AGB29XX_ATTR_IVILXISYNC_ARM_SOURCE_COUNT ViInt32 g 
 "The number of sources."

3 all "Arm Source Detection" AGB29XX_ATTR_IVILXISYNC_ARM_SOURCE_DETECTION ViInt32 gs ArmSourceDetection
 "Specifies the style of arm source detection."

3 all "Arm Source Enabled" AGB29XX_ATTR_IVILXISYNC_ARM_SOURCE_ENABLED ViBoolean gs 
 "Enables or disables the arm source."

3 all "Arm Source Event ID" AGB29XX_ATTR_IVILXISYNC_ARM_SOURCE_EVENTID ViString gs 
 "Specifies the LAN event identifier that is associated with this arm source.  LAN "
 "Events with this identifier are accepted from  the source described in the filter."

3 all "Arm Source Filter" AGB29XX_ATTR_IVILXISYNC_ARM_SOURCE_FILTER ViString gs 
 "Specifies a filter for restricting arm sources."

1 all "Event"

2 all "Event Count" AGB29XX_ATTR_IVILXISYNC_EVENT_COUNT ViInt32 g 
 "The number of available events."

2 all "Event Destination Path" AGB29XX_ATTR_IVILXISYNC_EVENT_DESTINATION_PATH ViString gs 
 "Specifies a list of places to send the event."

2 all "Event Drive Mode" AGB29XX_ATTR_IVILXISYNC_EVENT_DRIVE_MODE ViInt32 gs EventDriveMode
 "Specifies how this event is transmitted."

2 all "Event Slope" AGB29XX_ATTR_IVILXISYNC_EVENT_SLOPE ViInt32 gs SourceSlope
 "Specifies the slope of the inbound event that will cause the generation of an outbound "
 "event."

2 all "Event Source" AGB29XX_ATTR_IVILXISYNC_EVENT_SOURCE ViString gs 
 "Specifies the signal which causes an event to be transmitted."

1 all "Event Log"

2 all "Event Log Enabled" AGB29XX_ATTR_IVILXISYNC_EVENT_LOG_ENABLED ViBoolean gs 
 "Enables or disables the event logging feature."

2 all "Event Log Entry Count" AGB29XX_ATTR_IVILXISYNC_EVENT_LOG_ENTRY_COUNT ViInt32 g 
 "Returns the number of event log entries available."

1 all "Instrument Specific"

2 all "Display"

3 all "Color Set" AGB29XX_ATTR_DISPLAY_COLOR_SET ViInt32 gs 
 "Set/Get the color set of the front panel display."

3 all "Enabled" AGB29XX_ATTR_DISPLAY_ENABLED ViBoolean gs 
 "Enables or disables the front panel display in the remote operation."

3 all "Image Format" AGB29XX_ATTR_DISPLAY_IMAGE_FORMAT ViInt32 gs DisplayImageFormat
 "Set/Get the format of the image data."

3 all "Mode" AGB29XX_ATTR_DISPLAY_MODE ViInt32 gs DisplayMode
 "Sets/Gets the display mode."

3 all "Resolution" AGB29XX_ATTR_DISPLAY_RESOLUTION ViInt32 gs DisplayResolution
 "Sets/Gets the display resolution of the data displayed on the front panel display."

3 all "Zoom Enabled" AGB29XX_ATTR_DISPLAY_ZOOM_ENABLED ViBoolean gs 
 "Enables or disables the zoom function of the front panel display."

3 all "Window"

4 all "Message" AGB29XX_ATTR_WINDOW_MESSAGE ViString gs 
 "Sets/Gets the text message displayed on the center of the upper or lower half display "
 "area on the front panel display."

4 all "Message Enabled" AGB29XX_ATTR_WINDOW_MESSAGE_ENABLED ViBoolean gs 
 "Enables or Disables the text message."

4 all "Window Count" AGB29XX_ATTR_WINDOW_COUNT ViInt32 g 
 "Read Only - Returns the number of windows."

2 all "Event"

3 all "Domain" AGB29XX_ATTR_EVENT_DOMAIN ViInt32 gs 
 "Sets/Gets the LXI LAN domain."

3 all "EventID" AGB29XX_ATTR_EVENT_EVENTID ViString gs 
 "Sets/Gets the LAN event identifier that is associated with this arm source. LAN Events "
 "with this identifier are accepted from the source described in the filter."

2 all "Measurement"

3 all "Measurement Count" AGB29XX_ATTR_MEASUREMENT_COUNT ViInt32 g 
 "Read Only - Returns the number of measurements."

3 all "Offset" AGB29XX_ATTR_MEASUREMENT_OFFSET ViReal64 gs 
 "Sets/Gets the null offset value used for calculating the limit test data."

3 all "Offset Enabled" AGB29XX_ATTR_MEASUREMENT_OFFSET_ENABLED ViBoolean gs 
 "Enables or disables the null offset function used for calculating the limit test "
 "data."

3 all "Remote Sensing Enabled" AGB29XX_ATTR_MEASUREMENT_REMOTE_SENSING_ENABLED ViBoolean gs 
 "Enables or disables the remote sensing."

3 all "Trigger Output Enabled" AGB29XX_ATTR_MEASUREMENT_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the trigger "
 "layer and the acquire device action."

3 all "Arm"

4 all "Bypass" AGB29XX_ATTR_MEASUREMENT_ARM_BYPASS ViInt32 gs ArmTriggerBypass
 "Enables or disables a bypass for the event detector in the arm layer."

4 all "Count" AGB29XX_ATTR_MEASUREMENT_ARM_COUNT ViInt32 gs 
 "Sets/Gets the arm count for the specified device action. Valid arm count range is "
 "1 to 100000 or 2147483647. arm count = 2147483647 indicates infinity. Default arm "
 "count value is 1."

4 all "Delay" AGB29XX_ATTR_MEASUREMENT_ARM_DELAY ViReal64 gs 
 "Sets/Gets the arm delay for the specified device action."

4 all "Source" AGB29XX_ATTR_MEASUREMENT_ARM_SOURCE ViInt32 gs ArmTriggerSource
 "Sets/Gets the arm source for the specified device action."

4 all "Timer" AGB29XX_ATTR_MEASUREMENT_ARM_TIMER ViReal64 gs 
 "Sets/Gets the interval of the TIMer arm source for the specified device action."

4 all "Trigger Output Enabled" AGB29XX_ATTR_MEASUREMENT_ARM_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the idle state "
 "and the arm layer."

3 all "CompositeLimitTest"

4 all "Auto Clear Delay" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_AUTO_CLEAR_DELAY ViReal64 gs 
 "Sets/Gets the automatic clear delay for digital output."

4 all "Auto Clear Enabled" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_AUTO_CLEAR_ENABLED ViBoolean gs 
 "Enables or disables the automatic clear function of the composite limit test."

4 all "Enabled" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_ENABLED ViBoolean gs 
 "Enables or disables the composite limit test."

4 all "Operation Mode" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_OPERATION_MODE ViInt32 gs CompositeLimitTestMode
 "Sets/Gets the operation mode of the composite limit test to GRADing or SORTing."

4 all "Output Result Enabled" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_OUTPUT_RESULT_ENABLED ViBoolean gs 
 "Enables or disables the immediate result output or update."

4 all "Status" AGB29XX_ATTR_COMPOSITE_LIMIT_TEST_STATUS ViInt32 g 
 "Read Only - Checks if the present composite limit test contains a limit test which "
 "means a pass/fail judgement. 0: No limit test exists. 1: At least one limit test "
 "exists."

3 all "Current"

4 all "Aperture" AGB29XX_ATTR_MEASUREMENT_CURRENT_APERTURE ViReal64 gs 
 "Sets/Gets the integration time for one point measurement."

4 all "Aperture Auto Enabled" AGB29XX_ATTR_MEASUREMENT_CURRENT_APERTURE_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic aperture function."

4 all "Auto Range Enabled" AGB29XX_ATTR_MEASUREMENT_CURRENT_AUTO_RANGE_ENABLED ViBoolean gs 
 "Enables or disables the automatic ranging function of the specified measurement channel."

4 all "Auto Ranging Mode" AGB29XX_ATTR_MEASUREMENT_CURRENT_AUTO_RANGING_MODE ViInt32 gs MeasurementAutoRangingMode
 "Sets/Gets the operation mode of the automatic measurement ranging."

4 all "Auto Ranging Threshold" AGB29XX_ATTR_MEASUREMENT_CURRENT_AUTO_RANGING_THRESHOLD ViReal64 gs 
 "Sets/Gets the threshold rate for the advanced automatic measurement ranging operation."

4 all "Compliance Status Enabled" AGB29XX_ATTR_MEASUREMENT_CURRENT_COMPLIANCE_STATUS_ENABLED ViBoolean g 
 "Read Only - Returns the compliance status of the specified channel."

4 all "Compliance Value" AGB29XX_ATTR_MEASUREMENT_CURRENT_COMPLIANCE_VALUE ViReal64 gs 
 "Sets/Gets the compliance value of the specified channel. The setting value is applied "
 "to both positive and negative sides."

4 all "Compliance Value Negative" AGB29XX_ATTR_MEASUREMENT_CURRENT_COMPLIANCE_VALUE_NEGATIVE ViReal64 gs 
 "Sets/Gets the negative side compliance value of the specified channel."

4 all "Compliance Value Positive" AGB29XX_ATTR_MEASUREMENT_CURRENT_COMPLIANCE_VALUE_POSITIVE ViReal64 gs 
 "Sets/Gets the positive side compliance value of the specified channel."

4 all "NPLC" AGB29XX_ATTR_MEASUREMENT_CURRENT_NPLC ViReal64 gs 
 "Sets/Gets the number of power line cycles (NPLC) value instead of setting the integration "
 "time for one point measurement."

4 all "NPLC Auto Enabled" AGB29XX_ATTR_MEASUREMENT_CURRENT_NPLC_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic NPLC function."

4 all "Range" AGB29XX_ATTR_MEASUREMENT_CURRENT_RANGE ViReal64 gs 
 "Sets/Gets the expected measurement value and sets the measurement range which provides "
 "the best resolution to measure the specified value."

4 all "Range Lower Limit" AGB29XX_ATTR_MEASUREMENT_CURRENT_RANGE_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets the lower limit for the automatic measurement ranging operation and sets "
 "the minimum measurement range which provides the best resolution to measure the specified "
 "value."

4 all "Range Upper Limit" AGB29XX_ATTR_MEASUREMENT_CURRENT_RANGE_UPPER_LIMIT ViReal64 g 
 "Read Only - Gets the upper limit for the automatic measurement ranging operation "
 "and sets the maximum measurement range which provides the best resolution to measure "
 "the specified value."

3 all "Format"

4 all "Byte Order" AGB29XX_ATTR_FORMAT_BYTE_ORDER ViInt32 gs FormatByteOrder
 "Sets/Gets the byte order of a binary output data."

4 all "Type" AGB29XX_ATTR_FORMAT_TYPE ViInt32 gs FormatType
 "Sets/Gets the data output format."

3 all "Function"

4 all "Disable Count" AGB29XX_ATTR_FUNCTION_DISABLE_COUNT ViInt32 g 
 "Read Only - Returns the number of measurement functions that are disabled."

4 all "Enable Count" AGB29XX_ATTR_FUNCTION_ENABLE_COUNT ViInt32 g 
 "Read Only - Returns the number of measurement functions that are enabled."

3 all "LimitTest"

4 all "Enabled" AGB29XX_ATTR_LIMITTEST_ENABLED ViBoolean gs 
 "Enables or disables the limit test."

4 all "Input Data Value" AGB29XX_ATTR_LIMITTEST_INPUT_DATA_VALUE ViInt32 gs LimitTestInputDataValue
 "Sets/Gets the input data value used for calculating the limit test data."

4 all "LimitTest Count" AGB29XX_ATTR_LIMITTEST_COUNT ViInt32 g 
 "Read Only - Returns the number of limittests."

4 all "Lower Limit" AGB29XX_ATTR_LIMITTEST_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets a lower limit used for the limit test"

4 all "Pass Data" AGB29XX_ATTR_LIMITTEST_PASS_DATA ViInt32 gs 
 "Sets/Gets a bit pattern used to indicate pass of the limit test"

4 all "Result" AGB29XX_ATTR_LIMITTEST_RESULT ViBoolean g 
 "Read Only - Returns the result of the limit test"

4 all "Test Type" AGB29XX_ATTR_LIMITTEST_TEST_TYPE ViInt32 gs LimitTestType
 "Sets/Gets the type of the limit test"

4 all "Upper Limit" AGB29XX_ATTR_LIMITTEST_UPPER_LIMIT ViReal64 gs 
 "Sets/Gets a upper limit used for the limit test"

4 all "ComplianceStatusCheck"

5 all "Failure Data" AGB29XX_ATTR_COMPLIANCE_STATUS_CHECK_FAILURE_DATA ViInt32 gs 
 "Sets/Gets a bit pattern used to indicate failure of the compliance status check"

5 all "Judgement Criteria" AGB29XX_ATTR_COMPLIANCE_STATUS_CHECK_JUDGEMENT_CRITERIA ViInt32 gs LimitTestJudgementCriteria
 "Sets/Gets the judgement criteria of the compliance status check"

3 all "Math"

4 all "Enabled" AGB29XX_ATTR_MATH_ENABLED ViBoolean gs 
 "Enables or disables the math expression."

4 all "Expression" AGB29XX_ATTR_MATH_EXPRESSION ViString gs 
 "Sets/Gets a math expression which will be an user-defined math expression."

4 all "Expression Name" AGB29XX_ATTR_MATH_EXPRESSION_NAME ViString gs 
 "Sets/Gets a math expression used for calculation."

4 all "Unit Name" AGB29XX_ATTR_MATH_UNIT_NAME ViString gs 
 "Sets/Gets the unit name for the math expression."

3 all "Resistance"

4 all "Aperture" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_APERTURE ViReal64 gs 
 "Sets/Gets the integration time for one point measurement."

4 all "Aperture Auto Enabled" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_APERTURE_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic aperture function."

4 all "Auto Range Enabled" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_AUTO_RANGE_ENABLED ViBoolean gs 
 "Enables or disables the automatic ranging function of the specified measurement channel."

4 all "Mode" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_MODE ViInt32 gs MeasurementResistanceMode
 "Sets/Gets the resistance measurement mode."

4 all "Nplc" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_NPLC ViReal64 gs 
 "Sets/Gets the number of power line cycles (NPLC) value instead of setting the integration "
 "time for one point measurement."

4 all "Nplc Auto Enabled" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_NPLC_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic NPLC function."

4 all "Offset Compensation Enabled" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_OFFSET_COMPENSATION_ENABLED ViBoolean gs 
 "Enables or disables the offset-compensated resistance measurement."

4 all "Range" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_RANGE ViReal64 gs 
 "Sets/Gets the expected measurement value and sets the measurement range which provides "
 "the best resolution to measure the specified value."

4 all "Range Lower Limit" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_RANGE_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets the lower limit for the automatic measurement ranging operation and sets "
 "the minimum measurement range which provides the best resolution to measure the specified "
 "value."

4 all "Range Upper Limit" AGB29XX_ATTR_MEASUREMENT_RESISTANCE_RANGE_UPPER_LIMIT ViReal64 gs 
 "Sets/Gets the upper limit for the automatic measurement ranging operation and sets "
 "the maximum measurement range which provides the best resolution to measure the specified "
 "value."

3 all "Trace"

4 all "Buffer Control" AGB29XX_ATTR_TRACE_BUFFER_CONTROL ViInt32 gs TraceBufferControl
 "Sets/Gets the trace buffer control."

4 all "Data Count" AGB29XX_ATTR_TRACE_DATA_COUNT ViInt32 g 
 "Read Only - Returns the number of data in the trace buffer."

4 all "Data Type" AGB29XX_ATTR_TRACE_DATA_TYPE ViInt32 gs TraceDataType
 "Sets/Gets the data placed in the trace buffer."

4 all "Operation" AGB29XX_ATTR_TRACE_OPERATION ViInt32 gs TraceOperation
 "Sets/Gets the statistical operation performed by the StatisticalData property."

4 all "Size" AGB29XX_ATTR_TRACE_SIZE ViInt32 gs 
 "Sets/Gets the size of the trace buffer."

4 all "Time Stamp Format" AGB29XX_ATTR_TRACE_TIME_STAMP_FORMAT ViInt32 gs TraceTimeStampFormat
 "Sets/Gets the rule for reading the timestamp data in the trace buffer."

3 all "Trigger"

4 all "Bypass" AGB29XX_ATTR_MEASUREMENT_TRIGGER_BYPASS ViInt32 gs ArmTriggerBypass
 "Enables or disables a bypass for the event detector in the trigger layer."

4 all "Count" AGB29XX_ATTR_MEASUREMENT_TRIGGER_COUNT ViInt32 gs 
 "Sets/Gets the trigger count for the specified device action. Valid trigger count "
 "range is 1 to 100000 or 2147483647. trigger count = 2147483647 indicates infinity. "
 "Default trigger count value is 1."

4 all "Delay" AGB29XX_ATTR_MEASUREMENT_TRIGGER_DELAY ViReal64 gs 
 "Sets/Gets the trigger delay for the specified device action."

4 all "Output Enabled" AGB29XX_ATTR_MEASUREMENT_TRIGGER_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the arm layer "
 "and the trigger layer."

4 all "Source" AGB29XX_ATTR_MEASUREMENT_TRIGGER_SOURCE ViInt32 gs ArmTriggerSource
 "Sets/Gets the trigger source for the specified device action."

4 all "Timer" AGB29XX_ATTR_MEASUREMENT_TRIGGER_TIMER ViReal64 gs 
 "Sets/Gets the interval of the TIMer trigger source for the specified device action."

3 all "Voltage"

4 all "Aperture" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_APERTURE ViReal64 gs 
 "Sets/Gets the integration time for one point measurement."

4 all "Aperture Auto Enabled" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_APERTURE_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic aperture function."

4 all "Auto Range Enabled" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_AUTO_RANGE_ENABLED ViBoolean gs 
 "Enables or disables the automatic ranging function of the specified measurement channel."

4 all "Auto Ranging Mode" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_AUTO_RANGING_MODE ViInt32 gs MeasurementAutoRangingMode
 "Sets/Gets the operation mode of the automatic measurement ranging."

4 all "Auto Ranging Threshold" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_AUTO_RANGING_THRESHOLD ViReal64 gs 
 "Sets/Gets the threshold rate for the advanced automatic measurement ranging operation."

4 all "Compliance Enabled" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_COMPLIANCE_STATUS_ENABLED ViBoolean g 
 "Read Only - Returns the compliance status of the specified channel."

4 all "Compliance Value" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_COMPLIANCE_VALUE ViReal64 gs 
 "Sets/Gets the compliance value of the specified channel. The setting value is applied "
 "to both positive and negative sides."

4 all "Compliance Value Negative" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_COMPLIANCE_VALUE_NEGATIVE ViReal64 gs 
 "Sets/Gets the negative side compliance value of the specified channel."

4 all "Compliance Value Positive" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_COMPLIANCE_VALUE_POSITIVE ViReal64 gs 
 "Sets/Gets the positive side compliance value of the specified channel."

4 all "Nplc" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_NPLC ViReal64 gs 
 "Sets/Gets the number of power line cycles (NPLC) value instead of setting the integration "
 "time for one point measurement."

4 all "Nplc Auto Enabled" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_NPLC_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic NPLC function."

4 all "Range" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_RANGE ViReal64 gs 
 "Sets/Gets the expected measurement value and sets the measurement range which provides "
 "the best resolution to measure the specified value."

4 all "Range Lower Limit" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_RANGE_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets the lower limit for the automatic measurement ranging operation and sets "
 "the minimum measurement range which provides the best resolution to measure the specified "
 "value."

4 all "Range upper Limit" AGB29XX_ATTR_MEASUREMENT_VOLTAGE_RANGE_UPPER_LIMIT ViReal64 g 
 "Read Only - Gets the upper limit for the automatic measurement ranging operation "
 "and sets the maximum measurement range which provides the best resolution to measure "
 "the specified value."

3 all "WaitTime"

4 all "Auto Enabled" AGB29XX_ATTR_MEASUREMENT_WAIT_TIME_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the initial wait time used for calculating the measurement wait "
 "time for the specified channel."

4 all "Enabled" AGB29XX_ATTR_MEASUREMENT_WAIT_TIME_ENABLED ViBoolean gs 
 "Enables or disables the measurement wait time for the specified channel."

4 all "Gain" AGB29XX_ATTR_MEASUREMENT_WAIT_TIME_GAIN ViReal64 gs 
 "Sets/Gets the gain value used for calculating the measurement wait time for the specified "
 "channel."

4 all "Offset" AGB29XX_ATTR_MEASUREMENT_WAIT_TIME_OFFSET ViReal64 gs 
 "Sets/Gets the offset value used for calculating the measurement wait time for the "
 "specified channel."

2 all "Memory"

3 all "Change Directory" AGB29XX_ATTR_MEMORY_CHANGE_DIRECTORY ViString gs 
 "Set property changes the current directory to the specified directory.  Get property "
 "returns the full path of Current directory."

2 all "Output"

3 all "Auto Off Enabled" AGB29XX_ATTR_OUTPUT_AUTO_OFF_ENABLED ViBoolean gs 
 "Enables or disables the automatic output off function."

3 all "Auto On Enabled" AGB29XX_ATTR_OUTPUT_AUTO_ON_ENABLED ViBoolean gs 
 "Enables or disables the automatic output on function."

3 all "Enabled" AGB29XX_ATTR_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the source output."

3 all "High Cap Mode Enabled" AGB29XX_ATTR_OUTPUT_HIGH_CAP_MODE_ENABLED ViBoolean gs 
 "Enables or disables the high capacitance mode."

3 all "Low Terminal State" AGB29XX_ATTR_OUTPUT_LOW_TERMINAL_STATE ViInt32 gs OutputLowTerminalState
 "Sets/Gets the state of the low terminal."

3 all "Off Condition" AGB29XX_ATTR_OUTPUT_OFF_CONDITION ViInt32 gs OutputOffCondition
 "Sets/Gets the source condition after output off."

3 all "Output Count" AGB29XX_ATTR_OUTPUT_CHANNEL_COUNT ViInt32 g 
 "Returns the number of output channels."

3 all "Protection Enabled" AGB29XX_ATTR_OUTPUT_PROTECTION_ENABLED ViBoolean gs 
 "Enables or disables the automatic output off at compliance function."

3 all "Pulse Delay" AGB29XX_ATTR_OUTPUT_PULSE_DELAY ViReal64 gs 
 "Sets/Gets the pulse delay time for the specified channel."

3 all "Pulse Width" AGB29XX_ATTR_OUTPUT_PULSE_WIDTH ViReal64 gs 
 "Sets/Gets the pulse width for the specified channel."

3 all "Recall Setup" AGB29XX_ATTR_OUTPUT_RECALL_SETUP ViInt32 s 
 "Recalls the channel setup saved by the Save setup method."

3 all "Save Setup" AGB29XX_ATTR_OUTPUT_SAVE_SETUP ViInt32 s 
 "Saves the channel setup."

3 all "Shape" AGB29XX_ATTR_OUTPUT_SHAPE ViInt32 gs OutputShape
 "Sets/Gets the source output shape of the specified channel."

3 all "Type" AGB29XX_ATTR_OUTPUT_TYPE ViInt32 gs OutputType
 "Sets/Gets the source output mode of the specified channel."

3 all "Current"

4 all "Auto Range Enabled" AGB29XX_ATTR_OUTPUT_CURRENT_AUTO_RANGE_ENABLED ViBoolean gs 
 "Enables or disables the automatic ranging function of the specified source channel."

4 all "Level" AGB29XX_ATTR_OUTPUT_CURRENT_LEVEL ViReal64 gs 
 "Sets/Gets the output level of the specified source channel immediately."

4 all "Range" AGB29XX_ATTR_OUTPUT_CURRENT_RANGE ViReal64 gs 
 "Sets/Gets the current output range of the specified source channel."

4 all "Range Lower Limit" AGB29XX_ATTR_OUTPUT_CURRENT_RANGE_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets the lower limit for the automatic output ranging operation"

4 all "Triggered Level" AGB29XX_ATTR_OUTPUT_CURRENT_TRIGGERED_LEVEL ViReal64 gs 
 "Sets/Gets the output level of the specified source channel immediately by receiving "
 "a trigger source."

3 all "Filter"

4 all "Auto Enabled" AGB29XX_ATTR_OUTPUT_FILTER_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the automatic filter function."

4 all "Cut Off Frequency" AGB29XX_ATTR_OUTPUT_FILTER_CUT_OFF_FREQUENCY ViReal64 gs 
 "Sets/Gets the cutoff frequency of the output filter"

4 all "Enabled" AGB29XX_ATTR_OUTPUT_FILTER_ENABLED ViBoolean gs 
 "Enables or disables the output filter."

4 all "External" AGB29XX_ATTR_OUTPUT_FILTER_EXTERNAL ViInt32 gs ExternalFilter
 "Sets/Gets the external filter type."

4 all "External Enabled" AGB29XX_ATTR_OUTPUT_FILTER_EXTERNAL_ENABLED ViBoolean gs 
 "Enables or disables the external filter."

4 all "Time Constant" AGB29XX_ATTR_OUTPUT_FILTER_TIME_CONSTANT ViReal64 gs 
 "Sets/Gets the time constant instead of setting the cutoff frequency of the output "
 "filter"

3 all "Resistance"

4 all "Enabled" AGB29XX_ATTR_OUTPUT_RESISTANCE_ENABLED ViBoolean gs 
 "Enables or disables the programmable output resistance."

4 all "Operation Mode" AGB29XX_ATTR_OUTPUT_RESISTANCE_OPERATION_MODE ViInt32 gs OutputResistanceOperationMode
 "Sets/Gets the operation mode of the programmable output resistance."

4 all "Series" AGB29XX_ATTR_OUTPUT_RESISTANCE_SERIES ViReal64 gs 
 "Sets/Gets the series resistance used for the fixed mode operation of the programmable "
 "output resistance."

4 all "Shunt" AGB29XX_ATTR_OUTPUT_RESISTANCE_SHUNT ViReal64 gs 
 "Sets/Gets the shunt resistance used for the fixed mode operation of the programmable "
 "output resistance."

3 all "Voltage"

4 all "Auto Range Enabled" AGB29XX_ATTR_OUTPUT_VOLTAGE_AUTO_RANGE_ENABLED ViBoolean gs 
 "Enables or disables the automatic ranging function of the specified source channel."

4 all "Level" AGB29XX_ATTR_OUTPUT_VOLTAGE_LEVEL ViReal64 gs 
 "Sets/Gets the output level of the specified source channel immediately."

4 all "Range" AGB29XX_ATTR_OUTPUT_VOLTAGE_RANGE ViReal64 gs 
 "Sets/Gets the voltage output range of the specified source channel."

4 all "Range Lower Limit" AGB29XX_ATTR_OUTPUT_VOLTAGE_RANGE_LOWER_LIMIT ViReal64 gs 
 "Sets/Gets the lower limit for the automatic output ranging operation"

4 all "Triggered Level" AGB29XX_ATTR_OUTPUT_VOLTAGE_TRIGGERED_LEVEL ViReal64 gs 
 "Sets/Gets the output level of the specified source channel immediately by receiving "
 "a trigger source."

3 all "WaitTime"

4 all "Auto Enabled" AGB29XX_ATTR_OUTPUT_WAIT_TIME_AUTO_ENABLED ViBoolean gs 
 "Enables or disables the initial wait time used for calculating the source wait time "
 "for the specified channel. The initial wait time is automatically set by the instrument "
 "and cannot be changed."

4 all "Enabled" AGB29XX_ATTR_OUTPUT_WAIT_TIME_ENABLED ViBoolean gs 
 "Enables or disables the source wait time for the specified channel."

4 all "Gain" AGB29XX_ATTR_OUTPUT_WAIT_TIME_GAIN ViReal64 gs 
 "Sets/Gets the gain value used for calculating the source wait time for the specified "
 "channel."

4 all "Offset" AGB29XX_ATTR_OUTPUT_WAIT_TIME_OFFSET ViReal64 gs 
 "Sets/Gets the offset value used for calculating the source wait time for the specified "
 "channel."

2 all "Program"

3 all "Catalog" AGB29XX_ATTR_PROGRAM_CATALOG ViString g 
 "Read Only -Returns the names of all programs defined in the program memory."

3 all "Name" AGB29XX_ATTR_PROGRAM_NAME ViString gs 
 "String containing the name of the program."

3 all "Status" AGB29XX_ATTR_PROGRAM_STATUS ViInt32 gs ProgramStatus
 "Changes the execution status of a program stored in the program memory. Values from "
 "AgB29xxProgramStatusEnum are used."

2 all "Status"

3 all "Serial Poll" AGB29XX_ATTR_STATUS_SERIAL_POLL ViInt32 g 
 "Read Only -Serial poll the instrument status byte."

2 all "System"

3 all "Auto Timer Reset Enabled" AGB29XX_ATTR_SYSTEM_AUTO_TIMER_RESET_ENABLED ViBoolean gs 
 "Enables or disables the automatic reset function of the timer."

3 all "Beeper Enabled" AGB29XX_ATTR_SYSTEM_BEEPER_ENABLED ViBoolean gs 
 "Enables or disables the beeper."

3 all "Date" AGB29XX_ATTR_SYSTEM_DATE ViString gs 
 "Current date formatted as 'YYYY, MM, DD'. YYYY is a four-digit representation of "
 "the year including century and millennium information. MM is a two-digit representation "
 "of the month where January is 1 and December is 12. DD is the day of the month."

3 all "Digital Port" AGB29XX_ATTR_SYSTEM_DIGITAL_PORT ViInt32 gs 
 "Sets/Gets the output data to the GPIO pins (digital control port)."

3 all "Line Frequency" AGB29XX_ATTR_SYSTEM_LINE_FREQUENCY ViInt32 gs 
 "Sets/Gets the line frequency."

3 all "Serial Number" AGB29XX_ATTR_SYSTEM_SERIAL_NUMBER ViString g 
 "Read Only -Instrument serial number."

3 all "System Io Timeout" AGB29XX_ATTR_SYSTEM_IO_TIMEOUT ViInt32 gs 
 "The I/O timeout in milliseconds.  The client program should normally not need to "
 "set the timeout.  Driver methods  with operations which take a significant time to "
 "perform are responsible for adjusting the I/O timeout to an appropriate value."

3 all "Time" AGB29XX_ATTR_SYSTEM_TIME ViString gs 
 "Current time formatted as 'HH, MM, SS.SSS'. HH is the hour and its range is 0 to "
 "23 inclusive. MM is the minute and its range is 0 to 59 inclusive. SS is the second "
 "in the range 0 to 59.999."

3 all "Timeout Milliseconds" AGB29XX_ATTR_SYSTEM_TIMEOUT_MILLISECONDS ViInt32 gs 
 "The value, in milliseconds, of the default timeout used by I/O operations. This property "
 "provides access to the driver's Visa Session Timeout.  Only in rare, unusual circumstances "
 "should the client set this property. Driver methods and properties with operations "
 "which take a significant time to perform are responsible for adjusting the I/O timeout "
 "to an appropriate value. Some methods provide a MaxTimeMilliseconds parameter which "
 "gives the client direct control over the timeout value for that method. Sometimes, "
 "however, increasing the timeout value can work around an obscure driver defect."

3 all "Timer Count" AGB29XX_ATTR_SYSTEM_TIMER_COUNT ViReal64 g 
 "Read Only -Returns the present count of the timer."

3 all "Trace Enabled" AGB29XX_ATTR_SYSTEM_TRACE_ENABLED ViBoolean gs 
 "If true, outputs a trace log of all driver calls to an xml file in the same directory "
 "as the application executable accessing the driver.  Generates default unique file "
 "names based on date and time.  A new file is generated each time the driver is initialized. "
 " You may specify the trace file name using 'TraceName=' the 'DriverSetup=' option "
 "string parameter to the Initialize() method.  For example: 'DriverSetup= TraceName=TraceOutput'"

3 all "Version" AGB29XX_ATTR_SYSTEM_VERSION ViString g 
 "Read Only -Returns the version of the SCPI standard."

2 all "Transient"

3 all "Transient Count" AGB29XX_ATTR_TRANSIENT_COUNT ViInt32 g 
 "Read Only -Returns the number of transients."

3 all "Trigger Output Enabled" AGB29XX_ATTR_TRANSIENT_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the trigger "
 "layer and the transient device action."

3 all "ArbitraryWaveform"

4 all "Count" AGB29XX_ATTR_ARBITRARYWAVEFORM_COUNT ViInt32 gs 
 "Sets/Gets the number of arbitrary waveform for the current/voltage output. Valid "
 "waveform count range is 1 to 100000 or 2147483647. waveform count = 2147483647 indicates "
 "infinity. default waveform count is 1."

4 all "Shape" AGB29XX_ATTR_ARBITRARYWAVEFORM_SHAPE ViInt32 gs TransientArbitraryWaveformShape
 "Sets/Gets the shape of the arbitrary waveform output for the specified source channel."

4 all "Current"

5 all "Exponent"

6 all "End Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_EXPONENT_END_LEVEL ViReal64 gs 
 "Sets/Gets the end level of the exponential waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_EXPONENT_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the exponential waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_EXPONENT_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the exponential waveform output."

6 all "Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_EXPONENT_TIME ViReal64 gs 
 "Sets/Gets the time of the exponential waveform output."

6 all "Time Constant" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_EXPONENT_TIME_CONSTANT ViReal64 gs 
 "Sets/Gets the time constant of the exponential waveform output."

5 all "Ramp"

6 all "End Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_RAMP_END_LEVEL ViReal64 gs 
 "Sets/Gets the end level of the ramp waveform output."

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_RAMP_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the ramp waveform output."

6 all "Ramp Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_RAMP_RAMP_TIME ViReal64 gs 
 "Sets/Gets the ramp time of the ramp waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_RAMP_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the ramp waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_RAMP_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the ramp waveform output."

5 all "Sinusoid"

6 all "Amplitude" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SINUSOID_AMPLITUDE ViReal64 gs 
 "Sets/Gets the amplitude of the sinusoidal waveform output."

6 all "Frequency" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SINUSOID_FREQUENCY ViReal64 gs 
 "Sets/Gets the frequency of the sinusoidal waveform output."

6 all "Offset" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SINUSOID_OFFSET ViReal64 gs 
 "Sets/Gets the offset level of the sinusoidal waveform output."

6 all "Phase Marker" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SINUSOID_PHASE_MARKER ViReal64 gs 
 "Sets/Gets Specifies the position of the phase marker for the sinusoidal waveform "
 "output."

6 all "Trigger Output Enabled" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SINUSOID_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output at the phase marker of the sinusoidal waveform "
 "output."

5 all "Square"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SQUARE_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the square waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SQUARE_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the square waveform output."

6 all "Peak Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SQUARE_PEAK_TIME ViReal64 gs 
 "Sets/Gets the peak time of the square waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SQUARE_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the square waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_SQUARE_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the square waveform output."

5 all "Trapezoid"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the trapezoidal waveform output."

6 all "Fall Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_FALL_TIME ViReal64 gs 
 "Sets/Gets the fall time of the trapezoidal waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the trapezoidal waveform output."

6 all "Peak Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_PEAK_TIME ViReal64 gs 
 "Sets/Gets the peak time of the trapezoidal waveform output."

6 all "Rise Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_RISE_TIME ViReal64 gs 
 "Sets/Gets the rise time of the trapezoidal waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the trapezoidal waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRAPEZOID_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the trapezoidal waveform output."

5 all "Triangle"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the triangle waveform output."

6 all "Fall Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_FALL_TIME ViReal64 gs 
 "Sets/Gets the fall time of the triangle waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the triangle waveform output."

6 all "Rise Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_RISE_TIME ViReal64 gs 
 "Sets/Gets the rise time of the triangle waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the triangle waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_CURRENT_TRIANGLE_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the triangle waveform output."

4 all "UserWaveform"

5 all "UserWaveform Count" AGB29XX_ATTR_USERWAVEFORM_COUNT ViInt32 g 
 "Returns the number of userwaveforms."

5 all "Current"

6 all "Current List Points" AGB29XX_ATTR_USERWAVEFORM_CURRENT_CURRENT_LIST_POINTS ViInt32 g 
 "READ ONLY Returns the number of data in the list set by the ConfigureCurrent list "
 "method."

6 all "Step Time" AGB29XX_ATTR_USERWAVEFORM_CURRENT_STEP_TIME ViReal64 gs 
 "Sets/Gets the step time of the user-defined waveform."

6 all "Trigger Enabled" AGB29XX_ATTR_USERWAVEFORM_CURRENT_TRIGGER_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the user-defined waveform output."

6 all "Trigger List Points" AGB29XX_ATTR_USERWAVEFORM_CURRENT_TRIGGER_LIST_POINTS ViInt32 g 
 "READ ONLY Returns the number of data in the list set by the ConfigureTrigger list "
 "method."

5 all "Voltage"

6 all "Step Time" AGB29XX_ATTR_USERWAVEFORM_VOLTAGE_STEP_TIME ViReal64 gs 
 "Sets/Gets the step time of the user-defined waveform."

6 all "Trigger Enabled" AGB29XX_ATTR_USERWAVEFORM_VOLTAGE_TRIGGER_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the user-defined waveform output."

6 all "Trigger List Points" AGB29XX_ATTR_USERWAVEFORM_VOLTAGE_TRIGGER_LIST_POINTS ViInt32 g 
 "Read Only - Returns the number of data in the list set by the ConfigureTrigger list "
 "method."

6 all "Voltage List Points" AGB29XX_ATTR_USERWAVEFORM_VOLTAGE_VOLTAGE_LIST_POINTS ViInt32 g 
 "Read Only - Returns the number of data in the list set by the ConfigureVoltagelist "
 "method."

4 all "Voltage"

5 all "Exponent"

6 all "End Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_EXPONENT_END_LEVEL ViReal64 gs 
 "Sets/Gets the end level of the exponential waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_EXPONENT_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the exponential waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_EXPONENT_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the exponential waveform output."

6 all "Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_EXPONENT_TIME ViReal64 gs 
 "Sets/Gets the time of the exponential waveform output."

6 all "Time Constant" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_EXPONENT_TIME_CONSTANT ViReal64 gs 
 "Sets/Gets the time constant of the exponential waveform output."

5 all "Ramp"

6 all "End Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_RAMP_END_LEVEL ViReal64 gs 
 "Sets/Gets the end level of the ramp waveform output."

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_RAMP_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the ramp waveform output."

6 all "Ramp Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_RAMP_RAMP_TIME ViReal64 gs 
 "Sets/Gets the ramp time of the ramp waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_RAMP_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the ramp waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_RAMP_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the ramp waveform output."

5 all "Sinusoid"

6 all "Amplitude" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SINUSOID_AMPLITUDE ViReal64 gs 
 "Sets/Gets the amplitude of the sinusoidal waveform output."

6 all "Frequency" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SINUSOID_FREQUENCY ViReal64 gs 
 "Sets/Gets the frequency of the sinusoidal waveform output."

6 all "Offset" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SINUSOID_OFFSET ViReal64 gs 
 "Sets/Gets the offset level of the sinusoidal waveform output."

6 all "Phase Marker" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SINUSOID_PHASE_MARKER ViReal64 gs 
 "Sets/Gets Specifies the position of the phase marker for the sinusoidal waveform "
 "output."

6 all "Trigger Output Enabled" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SINUSOID_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output at the phase marker of the sinusoidal waveform "
 "output."

5 all "Square"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SQUARE_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the square waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SQUARE_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the square waveform output."

6 all "Peak Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SQUARE_PEAK_TIME ViReal64 gs 
 "Sets/Gets the peak time of the square waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SQUARE_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the square waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_SQUARE_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the square waveform output."

5 all "Trapezoid"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the trapezoidal waveform output."

6 all "Fall Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_FALL_TIME ViReal64 gs 
 "Sets/Gets the fall time of the trapezoidal waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the trapezoidal waveform output."

6 all "Peak Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_PEAK_TIME ViReal64 gs 
 "Sets/Gets the peak time of the trapezoidal waveform output."

6 all "Rise Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_RISE_TIME ViReal64 gs 
 "Sets/Gets the rise time of the trapezoidal waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the trapezoidal waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRAPEZOID_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the trapezoidal waveform output."

5 all "Triangle"

6 all "End Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_END_TIME ViReal64 gs 
 "Sets/Gets the end time of the triangle waveform output."

6 all "Fall Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_FALL_TIME ViReal64 gs 
 "Sets/Gets the fall time of the triangle waveform output."

6 all "Peak Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_PEAK_LEVEL ViReal64 gs 
 "Sets/Gets the peak level of the triangle waveform output."

6 all "Rise Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_RISE_TIME ViReal64 gs 
 "Sets/Gets the rise time of the triangle waveform output."

6 all "Start Level" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_START_LEVEL ViReal64 gs 
 "Sets/Gets the start level of the triangle waveform output."

6 all "Start Time" AGB29XX_ATTR_ARBITRARYWAVEFORM_VOLTAGE_TRIANGLE_START_TIME ViReal64 gs 
 "Sets/Gets the start time of the triangle waveform output."

3 all "Arm"

4 all "Bypass" AGB29XX_ATTR_TRANSIENT_ARM_BYPASS ViInt32 gs ArmTriggerBypass
 "Enables or disables a bypass for the event detector in the arm layer."

4 all "Count" AGB29XX_ATTR_TRANSIENT_ARM_COUNT ViInt32 gs 
 "Sets/Gets the arm count for the specified device action. Valid arm count range is "
 "1 to 100000 or 2147483647. arm count = 2147483647 indicates infinity. Default arm "
 "count value is 1."

4 all "Delay" AGB29XX_ATTR_TRANSIENT_ARM_DELAY ViReal64 gs 
 "Sets the arm delay for the specified device action."

4 all "Source" AGB29XX_ATTR_TRANSIENT_ARM_SOURCE ViInt32 gs ArmTriggerSource
 "Sets/Gets the arm source for the specified device action."

4 all "Timer" AGB29XX_ATTR_TRANSIENT_ARM_TIMER ViReal64 gs 
 "Sets the interval of the TIMer arm source for the specified device action."

4 all "Trigger Output Enabled" AGB29XX_ATTR_TRANSIENT_ARM_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the idle state "
 "and the arm layer."

3 all "Current"

4 all "Center" AGB29XX_ATTR_TRANSIENT_CURRENT_CENTER ViReal64 gs 
 "Sets/Gets the center value of the current sweep output."

4 all "List Points" AGB29XX_ATTR_TRANSIENT_CURRENT_LIST_POINTS ViInt32 g 
 "Read Only -Gets the number of sweep steps of the current sweep output."

4 all "Mode" AGB29XX_ATTR_TRANSIENT_CURRENT_MODE ViInt32 gs TransientCurrentVoltageMode
 "Sets/Gets the source mode, fixed, list sweep, or sweep, of the specified source channel."

4 all "Span" AGB29XX_ATTR_TRANSIENT_CURRENT_SPAN ViReal64 gs 
 "Sets/Gets the span value of the current sweep output."

4 all "Start" AGB29XX_ATTR_TRANSIENT_CURRENT_START ViReal64 gs 
 "Sets/Gets the start value of the current sweep output."

4 all "Step" AGB29XX_ATTR_TRANSIENT_CURRENT_STEP ViReal64 gs 
 "Sets/Gets the sweep step value of the current sweep output."

4 all "Stop" AGB29XX_ATTR_TRANSIENT_CURRENT_STOP ViReal64 gs 
 "Sets the stop value of the current sweep output."

4 all "Sweep Points" AGB29XX_ATTR_TRANSIENT_CURRENT_SWEEP_POINTS ViInt32 gs 
 "Sets/Gets the number of data in the list."

4 all "Sweep Start Point" AGB29XX_ATTR_TRANSIENT_CURRENT_SWEEP_START_POINT ViInt32 gs 
 "Sets/Gets the list sweep start point by using the index of the list."

3 all "Sweep"

4 all "Direction" AGB29XX_ATTR_SWEEP_DIRECTION ViInt32 gs SweepDirection
 "Sets/Gets the sweep direction UP or DOWN for the specified channel."

4 all "Mode" AGB29XX_ATTR_SWEEP_MODE ViInt32 gs SweepMode
 "Sets/Gets the sweep mode for the specified channel."

4 all "Output Ranging Mode" AGB29XX_ATTR_SWEEP_OUTPUT_RANGING_MODE ViInt32 gs SweepOutputRangingMode
 "Sets/Gets the output ranging mode of the sweep output for the specified channel."

4 all "Output Scale" AGB29XX_ATTR_SWEEP_OUTPUT_SCALE ViInt32 gs SweepOutputScale
 "Sets/Gets the scale of the sweep output for the specified channel."

3 all "Trigger"

4 all "Bypass" AGB29XX_ATTR_TRANSIENT_TRIGGER_BYPASS ViInt32 gs ArmTriggerBypass
 "Enables or disables a bypass for the event detector in the trigger layer."

4 all "Continuous Enabled" AGB29XX_ATTR_TRANSIENT_TRIGGER_CONTINUOUS_ENABLED ViBoolean gs 
 "Enables or disables the continuous trigger output for the specified channel."

4 all "Count" AGB29XX_ATTR_TRANSIENT_TRIGGER_COUNT ViInt32 gs 
 "Sets/Gets the trigger count for the specified device action. Valid trigger count "
 "range is 1 to 100000 or 2147483647. trigger count=2147483647 indicates infinity. "
 "Default is 1."

4 all "Delay" AGB29XX_ATTR_TRANSIENT_TRIGGER_DELAY ViReal64 gs 
 "Sets/Gets the trigger delay for the specified device action."

4 all "Output Enabled" AGB29XX_ATTR_TRANSIENT_TRIGGER_TRIGGER_OUTPUT_ENABLED ViBoolean gs 
 "Enables or disables the trigger output for the status change between the arm layer "
 "and the trigger layer."

4 all "Source" AGB29XX_ATTR_TRANSIENT_TRIGGER_SOURCE ViInt32 gs ArmTriggerSource
 "Set/Get the trigger source.  Values from AgB29xxArmTriggerSourceEnum enum."

4 all "Timer" AGB29XX_ATTR_TRANSIENT_TRIGGER_TIMER ViReal64 gs 
 "Sets/Gets the interval of the Timer trigger source for the specified device action."

3 all "Voltage"

4 all "Center" AGB29XX_ATTR_TRANSIENT_VOLTAGE_CENTER ViReal64 gs 
 "Sets/Gets the center value of the voltage sweep output."

4 all "List Points" AGB29XX_ATTR_TRANSIENT_VOLTAGE_LIST_POINTS ViInt32 g 
 "Read Only -Gets the number of sweep steps of the voltage sweep output."

4 all "Mode" AGB29XX_ATTR_TRANSIENT_VOLTAGE_MODE ViInt32 gs TransientCurrentVoltageMode
 "Sets/Gets the source mode, fixed, list sweep, or sweep, of the specified source channel."

4 all "Span" AGB29XX_ATTR_TRANSIENT_VOLTAGE_SPAN ViReal64 gs 
 "Sets/Gets the span value of the voltage sweep output."

4 all "Start" AGB29XX_ATTR_TRANSIENT_VOLTAGE_START ViReal64 gs 
 "Sets/Gets the start value of the voltage sweep output."

4 all "Step" AGB29XX_ATTR_TRANSIENT_VOLTAGE_STEP ViReal64 gs 
 "Sets/Gets the sweep step value of the voltage sweep output."

4 all "Stop" AGB29XX_ATTR_TRANSIENT_VOLTAGE_STOP ViReal64 gs 
 "Sets the stop value of the voltage sweep output."

4 all "Sweep Points" AGB29XX_ATTR_TRANSIENT_VOLTAGE_SWEEP_POINTS ViInt32 gs 
 "Sets/Gets the number of data in the list."

4 all "Sweep Start Point" AGB29XX_ATTR_TRANSIENT_VOLTAGE_SWEEP_START_POINT ViInt32 gs 
 "Sets/Gets the list sweep start point by using the index of the list."

2 all "Trigger"

3 all "TriggerSource"

4 all "Enabled" AGB29XX_ATTR_TRIGGER_SOURCE_ENABLED ViBoolean gs 
 "Enables or disables the trigger source."

1 all "Output"

2 all "Current Limit" AGB29XX_ATTR_CURRENT_LIMIT ViReal64 gs 
 "propety Current Limit specifies the output current limit. The units are Amps."

2 all "Current Limit Behavior" AGB29XX_ATTR_CURRENT_LIMIT_BEHAVIOR ViInt32 gs CurrentLimitBehavior
 "property Current Limit Behavior specifies the behavior of the power supply when the "
 "output current is equal to or greater than the value of the Current Limit property."

2 all "OutputChannel Count" AGB29XX_ATTR_CHANNEL_COUNT ViInt32 g 
 "property Count contains how many outputs this DC power supply has. It is also the "
 "maximum valid value for the Index parameter to the Name method of the Outputs interface."

2 all "OVP Enabled" AGB29XX_ATTR_OVP_ENABLED ViBoolean gs 
 "property OVP Enabled specifies whether the power supply provides over-voltage protection. "
 "If this property is set to True, the power supply disables the output when the output "
 "voltage is greater than or equal to the OVP Limit."

2 all "OVP Limit" AGB29XX_ATTR_OVP_LIMIT ViReal64 gs 
 "property OVP Limit specifies the voltage the power supply allows. The units are Volts."

2 all "Voltage Level" AGB29XX_ATTR_VOLTAGE_LEVEL ViReal64 gs 
 "property Voltage Level specifies the voltage level the DC power supply attempts to "
 "generate. The units are Volts."

1 all "Trigger"

2 all "Trigger Source" AGB29XX_ATTR_TRIGGER_SOURCE ViInt32 gs TriggerSource
 "property Source specifies the trigger source."

2 all "Triggered Voltage Level" AGB29XX_ATTR_TRIGGERED_VOLTAGE_LEVEL ViReal64 gs 
 "property Triggerd Voltage Level specifies the value to  which the power supply sets "
 "the voltage level after a trigger event occurs."

2 all "Source"

3 all "Trigger Source Count" AGB29XX_ATTR_IVILXISYNC_TRIGGER_SOURCE_COUNT ViInt32 g 
 "The number of sources."

3 all "Trigger Source Delay" AGB29XX_ATTR_IVILXISYNC_TRIGGER_SOURCE_DELAY ViReal64 gs 
 "Specifies the trigger source delay from when the trigger logic is satisfied until "
 "the device specific action (for instance a measurement) is triggered."

3 all "Trigger Source Detection" AGB29XX_ATTR_IVILXISYNC_TRIGGER_SOURCE_DETECTION ViInt32 gs TriggerSourceDetection
 "Specifies the slope of the trigger source."

3 all "Trigger Source Event ID" AGB29XX_ATTR_IVILXISYNC_TRIGGER_SOURCE_EVENTID ViString gs 
 "Specifies the LAN event identifier that is associated with this trigger source."

3 all "Trigger Source Filter" AGB29XX_ATTR_IVILXISYNC_TRIGGER_SOURCE_FILTER ViString gs 
 "Specifies a filter for restricting trigger sources."
